name: PyTest

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        UV_EXTRA_INDEX_URL: "https://download.pytorch.org/whl/cpu"
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true

      - name: Setup venv
        run: >
            uv venv
        
      - name: Install dependencies
        run: >
            uv pip install -e . --group dev 
            --index-url https://download.pytorch.org/whl/cpu 
            --extra-index-url https://pypi.org/simple

      - name: Run Pytest
        run: uv run --no-sync pytest
